#!/bin/sh
BINARY_PATH=./src/gmediarender
IFNAME="enp0s8"
UUID=$(openssl rand -hex 6)
IPADDR=$(ip addr show $IFNAME | grep 'inet ' | awk  '{print $2}' | sed 's/\/.*//g')
DEVICE_NAME="MuiltSpeaker_"$UUID

#echo $UUID
echo $IPADDR
echo $DEVICE_NAME

$BINARY_PATH -u "$UUID" -I "$IPADDR" -f "$DEVICE_NAME" --logfile=/dev/stdout
