CFLAGS = -mms-bitfields -IH:/my/code/ffmpeg/HelloSDL/include
LDFLAGS = -LH:/my/code/ffmpeg/HelloSDL/lib -lmingw32 -lSDL2main -lSDL2  -mwindows

HelloSDL.exe: hello.o
	gcc $^ -o $@ $(LDFLAGS)

%.o: %.c
	gcc $(CFLAGS) -o $@ -c $^

clean:
	del HelloSDL.exe *.o